FROM amazonlinux:2.0.20200207.1

RUN amazon-linux-extras install -y epel
RUN yum install -y epel-release
RUN rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN yum update -y
RUN yum install -y git tar unzip
RUN yum install --enablerepo remi -y httpd
RUN yum install --enablerepo remi -y php74 php74-php php74-php-mbstring php74-php-mysqlnd php74-php-intl php74-php-json php74-php-pdo php74-php-pecl-mcrypt php74-php-xml composer php74-php-pecl-xdebug php74-php-pecl-zip

RUN echo "xdebug.remote_host=host.docker.internal" >> /etc/opt/remi/php74/php.d/15-xdebug.ini
RUN echo "xdebug.remote_port=9001" >> /etc/opt/remi/php74/php.d/15-xdebug.ini
RUN echo "xdebug.remote_enable=1" >> /etc/opt/remi/php74/php.d/15-xdebug.ini
# RUN echo "xdebug.remote_autostart=1" >> /etc/opt/remi/php74/php.d/15-xdebug.ini
RUN echo "xdebug.remote_connect_back" >> /etc/opt/remi/php74/php.d/15-xdebug.ini
RUN echo "xdebug.remote_handler=dbgp" >> /etc/opt/remi/php74/php.d/15-xdebug.ini
RUN echo "xdebug.idekey=idekey" >> /etc/opt/remi/php74/php.d/15-xdebug.ini

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
RUN echo "source ~/.nvm/nvm.sh;nvm install v12.16.1" | bash
RUN echo "source ~/.nvm/nvm.sh" >> ~/.bashrc

RUN ln -sf /usr/bin/php74 /usr/bin/php

COPY docker/conf/app.conf /etc/httpd/conf.d/